spring.application.name=Gl1tch_st0re
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@database2025_high?TNS_ADMIN=/Users/jonat/MEGA/Duoc_UC/2026/FullStack/Unidad_2/EV2/accesos_oracle/Wallet_DATABASE2025
spring.datasource.username=GL1TCH_ST0RE
spring.datasource.password=BDY1102_P1.practica_1
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG